version: 2.1

orbs:
  node: circleci/node@4.6.0

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - node/install-npm:
          version: "7"
      - run: npm install
      - run: npm test
